# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nR-eHYvEFpwa6OjhTpdi50fjOvbkkIec
"""

!pip freeze > requirements.txt

#importing the necessary libraries
import pandas as pd #data import and manipulation
import numpy as np #Cleaner arrays
import seaborn as sns #Statistical visualisations
import matplotlib.pyplot as plt #visualisations
from sklearn.cluster import KMeans #Machine learning algorithm
import warnings #Allows to bypass warnings regarding depreciated functions
warnings.filterwarnings('ignore')
import streamlit as st

file_path='/content/1. Weather Data.csv' #direction of where the data is located
print(type(wdata)) # Check the current type of wdata

wdata=pd.read_csv(file_path) #loading the data

wdata.head() #Reviwing the top 5 rows of the data

wdata['Weather'].unique() #Reviewing all the unique events within the weather column

wdata.nunique() #COunt of all the unique events in all columns

wdata.count() #counting the number of populated rows for each column (Allows to see if there are colums with missing data)

wdata.info() #Information about the data

wdata['Weather'].value_counts() #Counting the different unique items in a column

wdata[wdata.Weather=='Clear'] #counting how many times a specific event occured in a column

wdata.groupby('Weather').get_group('Clear') #using groupby to organise based on a specific unique value

wdata.head(2) #Viewing the data

wdata.groupby('Wind Speed_km/h').get_group(4) #organising and filtering combined

wdata[wdata['Wind Speed_km/h']==4] #using logical operators to filter data

wdata.isnull().sum() #Counting the number of missing values for each column

#Renaming colums
wdata.rename(columns={'Weather':'Weather Condition'},inplace=True)

wdata

#Checking the mean visibility
wdata.rename(columns={'Visibility_km':'Average Visibility'},inplace=True)
wdata['Average Visibility'].mean()

wdata['Press_kPa'].std()

wdata['Rel Hum_%'].var()

#Looking at all the days where the weather condition was snow
wdata.groupby('Weather Condition').get_group('Snow')

wdata[wdata['Weather Condition']=='Snow']

wdata[wdata['Weather Condition'].str.contains('Snow')]

#Filtering based on multiple conditions
wdata[(wdata['Wind Speed_km/h']> 24) & (wdata['Average Visibility']==25)]



wdata.groupby('Weather Condition').mean(numeric_only=True)

#Minimum and maximum value of each column again)
wdata.groupby('Weather Condition').min(numeric_only=True)

wdata.groupby('Weather Condition').max(numeric_only=True)

wdata[wdata['Weather Condition']=='Fog']

wdata[(wdata['Weather Condition']== 'Clear') | (wdata['Average Visibility']>40)]

#Multi criteria logical operator functions
wdata[(wdata['Weather Condition']=='Clear') | (wdata['Average Visibility']==40) & (wdata['Rel Hum_%']>50)]

