# -*- coding: utf-8 -*-
"""Weather_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/BeginnerCoder114/Weather_Data_Analysis/blob/main/Weather_data_analysis.ipynb
"""



#importing the necessary libraries
import pandas as pd #data import and manipulation
import numpy as np #Cleaner arrays
import streamlit as st

wdata=pd.read_csv('1. Weather Data.csv')

wdata['Weather'].unique() #Reviewing all the unique events within the weather column

wdata.nunique()

wdata.count()

wdata.info() #Information about the data

wdata['Weather'].value_counts() #Counting the different unique items in a column

wdata[wdata.Weather=='Clear'] #counting how many times a specific event occured in a column

wdata.groupby('Weather').get_group('Clear') #using groupby to organise based on a specific unique value

wdata.groupby('Wind Speed_km/h').get_group(4) #organising and filtering combined

wdata[wdata['Wind Speed_km/h']==4] #using logical operators to filter data

wdata.isnull().sum() #Counting the number of missing values for each column

wdata.rename(columns={'Weather':'Weather Condition'},inplace=True)

wdata.rename(columns={'Visibility_km':'Average Visibility'},inplace=True)
wdata['Average Visibility'].mean()

wdata['Press_kPa'].std()

wdata['Rel Hum_%'].var()

wdata.groupby('Weather Condition').get_group('Snow')

wdata[wdata['Weather Condition']=='Snow']

wdata[(wdata['Wind Speed_km/h']> 24) & (wdata['Average Visibility']==25)]

wdata.groupby('Weather Condition').min(numeric_only=True)

wdata.groupby('Weather Condition').max(numeric_only=True)

wdata.groupby('Weather Condition').max(numeric_only=True)

wdata[wdata['Weather Condition']=='Fog']

wdata[(wdata['Weather Condition']== 'Clear') | (wdata['Average Visibility']>40)]

wdata[(wdata['Weather Condition']=='Clear') | (wdata['Average Visibility']==40) & (wdata['Rel Hum_%']>50)]

